Auto generated from templates by gromit

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,5 +1,5 @@
 # Generated by: gromit policy
-# Generated on: Fri Oct 27 04:32:45 UTC 2023
+# Generated on: Tue Nov 21 21:48:03 UTC 2023
 
 # Distribution channels covered by this workflow
 # - Ubuntu and Debian
@@ -52,26 +52,26 @@ jobs:
           git config --global url."https://${TOKEN}@github.com".insteadOf "https://github.com"
 
       - name: Checkout of tyk
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
         with:
           fetch-depth: 1
 
       - name: "Add Git safe.directory"
         run: git config --global --add safe.directory $GITHUB_WORKSPACE
 
-      - uses: docker/setup-qemu-action@v2
+      - uses: docker/setup-qemu-action@v3
 
-      - uses: docker/setup-buildx-action@v2
+      - uses: docker/setup-buildx-action@v3
 
       - name: Login to DockerHub
         if: startsWith(github.ref, 'refs/tags')
-        uses: docker/login-action@v2
+        uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
       - name: Login to Cloudsmith
         if: startsWith(github.ref, 'refs/tags')
-        uses: docker/login-action@v2
+        uses: docker/login-action@v3
         with:
           registry: docker.tyk.io
           username: ${{ secrets.CLOUDSMITH_USERNAME }}
@@ -112,7 +112,7 @@ jobs:
           RPMVERS: ${{ matrix.rpmvers }}
           PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
           DOCKER_CLI_EXPERIMENTAL: "enabled"
-      - uses: aws-actions/configure-aws-credentials@v2
+      - uses: aws-actions/configure-aws-credentials@v4
         with:
           role-to-assume: arn:aws:iam::754489498669:role/ecr_rw_tyk
           role-session-name: cipush
@@ -122,12 +122,14 @@ jobs:
 
       - uses: aws-actions/amazon-ecr-login@v1
         id: ecr
+        if: ${{ matrix.golang_cross == '1.19-bullseye' }}
         with:
           mask-password: 'true'
 
       - name: Docker metadata for CI
         id: metadata
-        uses: docker/metadata-action@v4
+        if: ${{ matrix.golang_cross == '1.19-bullseye' }}
+        uses: docker/metadata-action@v5
         with:
           images: ${{ steps.ecr.outputs.registry }}/tyk
           flavor: |
@@ -140,6 +142,7 @@ jobs:
             type=semver,pattern=v{{version}},prefix=v
 
       - name: CI push
+        if: ${{ matrix.golang_cross == '1.19-bullseye' }}
         shell: bash
         env:
           t: ${{ steps.metadata.outputs.tags }}
@@ -155,6 +158,7 @@ jobs:
           done
 
       - uses: actions/upload-artifact@v3
+        if: ${{ matrix.golang_cross == '1.19-bullseye' }}
         with:
           name: deb
           retention-days: 1
@@ -163,6 +167,7 @@ jobs:
             !dist/*PAYG*.deb
 
       - uses: actions/upload-artifact@v3
+        if: ${{ matrix.golang_cross == '1.19-bullseye' }}
         with:
           name: rpm
           retention-days: 1
@@ -183,20 +188,7 @@ jobs:
         include:
           - db: postgres15
             markers: "and not sql"
-
     steps:
-      - uses: actions/checkout@v3
-        with:
-          fetch-depth: 1
-
-      - name: Checkout of tyk-automated-tests
-        uses: actions/checkout@v3
-        with:
-          repository: TykTechnologies/tyk-automated-tests
-          token: ${{ secrets.ORG_GH_TOKEN }}
-          ref: ${{ startsWith(github.ref_name, 'release-') && github.ref_name || 'master' }}
-          path: tyk-automated-tests
-
       - uses: aws-actions/configure-aws-credentials@v2
         with:
           role-to-assume: arn:aws:iam::754489498669:role/ecr_rw_tyk
@@ -207,9 +199,11 @@ jobs:
         uses: aws-actions/amazon-ecr-login@v1
         with:
           mask-password: 'true'
+          mask-aws-account-id: 'true'
 
         # Only ${{ github.actor }} has access
         # See https://github.com/mxschmitt/action-tmate#use-registered-public-ssh-keys
+
       - name: Setup tmate session only in debug mode
         uses: mxschmitt/action-tmate@v3
         if: ${{ runner.debug == '1' }}
@@ -217,17 +211,22 @@ jobs:
           detached: true
           limit-access-to-actor: true
 
+      - name: fetch env from tyk-ci
+        env:
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          gh release download v1.2 --repo github.com/TykTechnologies/tyk-ci -O env.tgz
+          tar xzvf env.tgz
+
       - name: env up
         shell: bash
-        working-directory: tyk-automated-tests/ci/auto
+        working-directory: auto
         id: env_up
         env:
           t: ${{ needs.goreleaser.outputs.tags }}
           pull_policy: 'if_not_present'
-          # gw and dash use the same branch names
-          gw_dash_image_tag: ${{ ( (github.repository == 'TykTechnologies/tyk' || github.repository == 'TykTechnologies/tyk-analytics') && startsWith(github.ref_name, 'release-') ) && github.ref_name || 'master' }}
-          pump_image_tag: ${{ ( github.repository == 'TykTechnologies/tyk-pump' && startsWith(github.ref_name, 'release-') ) && github.ref_name || 'master' }}
-          sink_image_tag: ${{ ( github.repository == 'TykTechnologies/tyk-sink' && startsWith(github.ref_name, 'release-') ) && github.ref_name || 'master' }}
+          # default tag to use
+          default_image_tag: ${{ startsWith(github.ref_name, 'release-') && github.ref_name || 'master' }}
           GH_TOKEN: ${{ secrets.ORG_GH_TOKEN }}
           TYK_DB_LICENSEKEY: ${{ secrets.DASH_LICENSE }}
           TYK_MDCB_LICENSE: ${{ secrets.MDCB_LICENSE }}
@@ -237,14 +236,15 @@ jobs:
           echo First tag: ${tags[0]}
           # Start customising the env
           echo "registry=${{ steps.ecr.outputs.registry }}
-          tyk_image=\${registry}/tyk:${gw_dash_image_tag}
-          tyk_analytics_image=\${registry}/tyk-analytics:${gw_dash_image_tag}
-          tyk_sink_image=\${registry}/tyk-sink:${sink_image_tag}
-          tyk_pump_image=\${registry}/tyk-pump:${pump_image_tag}
+          tyk_image=\${registry}/tyk:${default_image_tag}
+          tyk_analytics_image=\${registry}/tyk-analytics:${default_image_tag}
+          tyk_sink_image=\${registry}/tyk-sink:${default_image_tag}
+          tyk_pump_image=\${registry}/tyk-pump:${default_image_tag}
           # override default above with just built tag
           tyk_image=${tags[0]}
-          tyk_alfa_image=${tags[0]}
-          tyk_beta_image=${tags[0]}
+          # alfa and beta have to come after the override
+          tyk_alfa_image=\${tyk_image}
+          tyk_beta_image=\${tyk_image}
           # base dir for config files
           confs_dir=./pro-ha
           # pick database to use
@@ -258,13 +258,66 @@ jobs:
           docker compose -p auto -f pro-ha.yml -f deps_pro-ha.yml -f ${{ matrix.db }}.yml --env-file versions.env --profile slave-datacenter up --quiet-pull -d
 
       - name: Run tests
-        working-directory: tyk-automated-tests/ci/auto
+        working-directory: auto
+        id: test_execution
         run: |
-          docker run --rm --network auto_default --env-file pytest.env \
-          ${{ steps.ecr.outputs.registry }}/tyk-automated-tests:${{ startsWith(github.ref_name, 'release-') && github.ref_name || 'master' }} \
-          pytest -c pytest_ci.ini --ci -m "not local and not dind ${{ matrix.markers }}" 
+          echo "## API tests ${{ matrix.db }} ${{ matrix.conf }}" >> $GITHUB_STEP_SUMMARY
+          if docker run --rm --network auto_default --env-file pytest.env -v ${{ github.workspace }}/reports:/app/reports \
+             ${{ steps.ecr.outputs.registry }}/tyk-automated-tests:${{ startsWith(github.ref_name, 'release-') && github.ref_name || 'master' }} \
+             pytest -c pytest_ci.ini --ci -m "not local and not dind ${{ matrix.markers }}" > tests.out; then
+               echo "All tests passed!" >> $GITHUB_STEP_SUMMARY
+          else
+               echo "::error title=API tests ${{ matrix.db }} ${{ matrix.conf }}::Test execution failed"
+               cat tests.out >> $GITHUB_STEP_SUMMARY
+               docker compose -p auto -f pro-ha.yml -f deps_pro-ha.yml -f ${{ matrix.db }}.yml --env-file versions.env logs tyk tyk-analytics
+               exit 1
+          fi
 
-# TODO: PR comment, using just one comment and updating, not a new comment each time
+      - name: Archive Integration tests report
+        if: ${{ always() }} 
+        uses: actions/upload-artifact@v3
+        with:
+            name: api-test-report
+            retention-days: 3
+            path: ${{ github.workspace }}/reports
+
+      - name: Fetch commit author
+        if: ${{ steps.test_execution.outcome != 'success' && !github.event.pull_request.draft }}            
+        run: echo "GIT_USER_EMAIL=$(git show -s --format='%ae' HEAD)" >> $GITHUB_ENV
+
+      - name: Fetch slack user
+        if: ${{ steps.test_execution.outcome != 'success' && !github.event.pull_request.draft }}   
+        id: fetch_slack_user
+        uses: TykTechnologies/github-actions/.github/actions/github-to-slack@main
+        with:
+          github_email: ${{ env.GIT_USER_EMAIL }}
+
+      - name: Notify slack
+        if: ${{ steps.test_execution.outcome != 'success' && !github.event.pull_request.draft }}
+        uses: rtCamp/action-slack-notify@v2
+        env:
+          SLACK_WEBHOOK: ${{ secrets.API_TEST_ALERT_SLACK_WEBHOOK }}
+          SLACK_COLOR: ${{ job.status }}
+          SLACK_TITLE: "Result: ${{ steps.test_execution.outcome }}"
+          SLACK_USERNAME: API INTEGRATION TESTS
+          SLACK_MESSAGE: "*Test*: ${{ matrix.db }}-${{ matrix.conf }}, *Author*: ${{ steps.fetch_slack_user.outputs.slack-user-name }}"
+          SLACK_FOOTER: "<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|SEE EXECUTION DETAILS HERE>"
+
+      - name: Comment on PR
+        if: ${{ always() && !github.event.pull_request.draft }}
+        uses: mshick/add-pr-comment@v2
+        with:
+          message: |
+            **API tests result - ${{ matrix.db }}-${{ matrix.conf }} env: ${{ steps.test_execution.outcome }}** ${{ env.STATUS }} 
+            Branch used: ${{ github.ref }}
+            Commit: ${{ github.event.after }} ${{ github.event.commits[0].message }}
+            Triggered by: ${{ github.event_name }} (@${{ github.actor }})
+            [Execution page](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
+          repo-token: ${{ secrets.ORG_GH_TOKEN }}
+          message-id: ${{ matrix.db }}-${{ matrix.conf }}
+        env:
+          STATUS: "${{ steps.test_execution.outcome == 'success' && ':white_check_mark:' || ':no_entry_sign:' }}"
+
 
   upgrade-deb:
     if: startsWith(github.ref, 'refs/tags')
@@ -287,7 +340,7 @@ jobs:
           - debian:bookworm
 
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
         with:
           fetch-depth: 1
 
@@ -295,9 +348,9 @@ jobs:
         with:
           name: deb
 
-      - uses: docker/setup-qemu-action@v2
+      - uses: docker/setup-qemu-action@v3
 
-      - uses: docker/setup-buildx-action@v2
+      - uses: docker/setup-buildx-action@v3
 
       - name: generate dockerfile
         run: |
@@ -316,7 +369,7 @@ jobs:
           ' > Dockerfile
 
       - name: install on ${{ matrix.distro }}
-        uses: docker/build-push-action@v4
+        uses: docker/build-push-action@v5
         with:
           context: "."
           platforms: linux/${{ matrix.arch }}
@@ -345,7 +398,7 @@ jobs:
           - registry.access.redhat.com/ubi9/ubi
 
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
         with:
           fetch-depth: 1
 
@@ -353,7 +406,7 @@ jobs:
         with:
           name: rpm
 
-      - uses: docker/setup-buildx-action@v2
+      - uses: docker/setup-buildx-action@v3
 
       - name: generate dockerfile
         run: |
@@ -373,7 +426,7 @@ jobs:
           ' > Dockerfile
 
       - name: install on ${{ matrix.distro }}
-        uses: docker/build-push-action@v4
+        uses: docker/build-push-action@v5
         with:
           context: "."
           file: Dockerfile
@@ -384,7 +437,7 @@ jobs:
       - name: Test the built container image with api functionality test.
         run: |
           docker run --network ${{ job.container.network }} --rm test-${{ matrix.distro }}
-
+  
   smoke-tests:
     needs:
       - goreleaser
@@ -394,9 +447,10 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
         with:
           fetch-depth: 1
+
       - uses: aws-actions/configure-aws-credentials@v2
         with:
           role-to-assume: arn:aws:iam::754489498669:role/ecr_rw_tyk
@@ -410,44 +464,34 @@ jobs:
 
       - name: Run ci/tests
         shell: bash
-        env:
+        env:        
           GITHUB_TAG: ${{ github.ref }}
           GATEWAY_IMAGE: ${{ steps.ecr.outputs.registry }}/tyk:sha-${{ github.sha }}
           PLUGIN_COMPILER_IMAGE: ${{ steps.ecr.outputs.registry }}/tyk-plugin-compiler:sha-${{ github.sha }}
         run: |
           set -eaxo pipefail
+          if [ ! -d smoke-tests ]; then
+             echo "::warning No repo specific smoke tests defined"
+          fi
+          if [ ! -d ci/tests ]; then
+             echo "::warning No ci tests defined"
+             exit 0
+          fi
           for d in ci/tests/*/
           do
               echo Attempting to test $d
               if [ -d $d ] && [ -e $d/test.sh ]; then
                   cd $d
-                  ./test.sh ${{ needs.goreleaser.outputs.tag }}
+                  ./test.sh ${{ steps.ecr.outputs.registry }}/tyk:sha-${{ github.sha }}
                   cd -
               fi
           done
-      - name: Run smoke-tests
-
-        # This job only runs whenever a tag is created. A tag is required
-        # for a functional plugin compiler build for when the GO_GET=1 env
-        # is provided. The plugin compiler cannot fetch the referenced
-        # commit from a PR, but requires a /heads or /tags reference.
-        #
-        # See https://github.com/golang/go/issues/31191 for more info.
-
-        if: startsWith(github.ref, 'refs/tags')
-        shell: bash
-        env:
-          GITHUB_TAG: ${{ github.ref }}
-          GATEWAY_IMAGE: ${{ steps.ecr.outputs.registry }}/tyk:sha-${{ github.sha }}
-          PLUGIN_COMPILER_IMAGE: ${{ steps.ecr.outputs.registry }}/tyk-plugin-compiler:sha-${{ github.sha }}
-        run: |
-          set -eaxo pipefail
           for d in smoke-tests/*/
           do
               echo Attempting to test $d
               if [ -d $d ] && [ -e $d/test.sh ]; then
                   cd $d
-                  ./test.sh ${{ needs.goreleaser.outputs.tag }}
+                  ./test.sh ${{ steps.ecr.outputs.registry }}/tyk:sha-${{ github.sha }}
                   cd -
               fi
           done
