TD-1044: Update sync-automation to pick commits.
These changes enable picking entire commits in case of
changes to code contained in the `ci/` directory.

diff --git a/.github/workflows/sync-automation.yml b/.github/workflows/sync-automation.yml
--- a/.github/workflows/sync-automation.yml
+++ b/.github/workflows/sync-automation.yml
@@ -22,9 +22,6 @@ on:
       - .github/workflows/ui-tests.yml
       - ci/**
 
-env:
-  FILES: ci .github/workflows/release.yml .github/dependabot.yml .github/workflows/del-env.yml .github/workflows/api-tests.yml .github/workflows/ui-tests.yml
-
 jobs:
   sync:
     runs-on: ubuntu-latest
@@ -41,13 +38,52 @@ jobs:
           token: ${{ secrets.ORG_GH_TOKEN }}
 
       - name: sync ${{matrix.branch}} from master
+        id: sync-changes
         run: |
           git fetch origin master
           git config --local user.email "wf-gen@tyk-ci"
           git config --local user.name "Bender"
-          for f in $FILES; do 
-            git checkout --theirs origin/master -- $f || true
-          done
-          git commit -a -m "[CI] Syncing release automation from master"
-          git push origin
-          echo "::debug::${FILES} syncd for ${{matrix.branch}}"
+          if git rebase --onto ${{ matrix.branch }} master ${{ github.sha }}; then
+            echo "::set-output name=status::success"
+            echo "::notice::Rebase Success"
+          else
+            echo "::set-output name=status::fail"
+            echo "::notice::Rebase Failed->Conflicts!"
+            exit 1
+          fi
+          prbranch=sync/auto/${{ matrix.branch }}-${{ github.run_id }}
+          git switch -c $prbranch
+          git push origin $prbranch
+          echo "::set-output name=prbranch::$prbranch"
+          echo "::debug::Commit ${{ github.sha }} syncd for ${{matrix.branch}}"
+          exit 0
+
+      - name: Create PR from the branch.
+        id: create-pr
+        if: steps.sync-changes.outputs.status == 'success'
+        uses: actions/github-script@v6
+        with:
+          script: |
+            const response = await github.rest.pulls.create({
+              title: '[CI] Sync automation: Syncing commits from master',
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              head: ${{ steps.sync-changes.outputs.prbranch }},
+              base: ${{ matrix.branch }},
+              body: ` PR auto generated by the CI Sync automation.
+                      Picks the commit ${{ github.sha }} from master
+                      Please make any additional changes required before
+                      merging. `});
+            github.rest.issues.addLabels({
+              owner:  context.repo.owner,
+              repo: context.repo.repo,
+              issue_number: response.data.number,
+              labels: ['sync-automation'] });
+
+      - name: Notify slack on conflicts.
+        if: steps.sync-changes.outputs.status == 'fail'
+        uses: rtCamp/action-slack-notify@v2
+        env:
+          SLACK_TITLE: 'Sync-automation'
+          SLACK_MESSAGE: 'Conflicts while syncing automation, commit: ${{ github.sha }}, branch: ${{ matrix.branch }}'
+          SLACK_WEBHOOK: ${{ secrets.SYNC_NOTIFY_SLACK_HOOK }}
