Update sync-automation with latest paths.

diff --git a/.github/workflows/sync-automation.yml b/.github/workflows/sync-automation.yml
--- a/.github/workflows/sync-automation.yml
+++ b/.github/workflows/sync-automation.yml
@@ -1,9 +1,14 @@
-# Generated by: gromit policy
-# Generated on: 2021-06-03 06:31:05.998191957 +0000 UTC
 
-# This workflow should only exist in master
-# Missing files are silently ignored. Most of the time this is what we want, older repos may not have some files
-# If fwd or backport branches do not exist, they will be created
+
+# Generated by: tyk-ci/wf-gen
+# Generated on: Monday 28 February 2022 10:17:25 AM UTC
+
+# Generation commands:
+# ./meta.zsh -repos tyk -title sync-automation -branch sync/td-876
+# m4 -E -DxSRC_BRANCH='master' -DxRELEASE_BRANCHES='release-4-lts, release-3.2.3, release-4' -DxAUTO_FILES='ci/goreleaser/goreleaser.yml ci/goreleaser/goreleaser-el7.yml ci/Dockerfile.std ci/Dockerfile.slim ci/aws/byol.pkr.hcl .github/workflows/release.yml .github/workflows/del-env.yml ci/terraform/outputs.tf .github/dependabot.yml ci/install/before_install.sh ci/install/post_install.sh ci/install/post_remove.sh ci/install/post_trans.sh .github/workflows/api-tests.yml'
+
+# This workflow will silently ignore FILES that are missing in master
+# Most of the time this is what we want, older repos may not have some files
 
 name: Sync automation
 
@@ -12,56 +17,35 @@ on:
     branches:
       - master
     paths:
-      - bin/unlock-agent.sh
-      - .goreleaser.yml
-      - Dockerfileg.std
-      - Dockerfile.slim
-      - aws/byol.pkr.hcl
       - .github/workflows/release.yml
-      - .github/workflows/del-env.yml
-      - integration/terraform/outputs.tf
-      - install/before_install.sh
-      - install/post_install.sh
-      - install/post_remove.sh
-      - images/*
+      - .github/workflows/api-tests.yml
+      - ci/*
 
+env:
+  FILES: ci/goreleaser/goreleaser.yml ci/goreleaser/goreleaser-el7.yml ci/Dockerfile.std ci/Dockerfile.slim ci/aws/byol.pkr.hcl .github/workflows/release.yml .github/workflows/del-env.yml ci/terraform/outputs.tf .github/dependabot.yml ci/install/before_install.sh ci/install/post_install.sh ci/install/post_remove.sh ci/install/post_trans.sh .github/workflows/api-tests.yml
+  
 jobs:
-
-
-
-  fwdport:
+  sync:
     runs-on: ubuntu-latest
 
     strategy:
       fail-fast: false
       matrix:
-        branch: 
-          - release-3.2
-          - release-3.2.0
+        branch: [ release-4-lts, release-3.2.3, release-4 ]
           
     steps:
       - uses: actions/checkout@v2
         with:
           ref: ${{matrix.branch}}
 
-      - name: Forward port master → ${{matrix.branch}}
+      - name: sync ${{matrix.branch}} from master
         run: |
-          git checkout ${{matrix.branch}} || git checkout -b ${{matrix.branch}}
-          git config --local user.email "policy@gromit"
+          git fetch origin master
+          git config --local user.email "wf-gen@tyk-ci"
           git config --local user.name "Bender"
-          git checkout --theirs origin/master -- bin/unlock-agent.sh
-          git checkout --theirs origin/master -- .goreleaser.yml
-          git checkout --theirs origin/master -- Dockerfileg.std
-          git checkout --theirs origin/master -- Dockerfile.slim
-          git checkout --theirs origin/master -- aws/byol.pkr.hcl
-          git checkout --theirs origin/master -- .github/workflows/release.yml
-          git checkout --theirs origin/master -- .github/workflows/del-env.yml
-          git checkout --theirs origin/master -- integration/terraform/outputs.tf
-          git checkout --theirs origin/master -- install/before_install.sh
-          git checkout --theirs origin/master -- install/post_install.sh
-          git checkout --theirs origin/master -- install/post_remove.sh
-          git checkout --theirs origin/master -- images/*
-          git commit -m "[CI] Fwdport release automation from master" -m "${{ github.event.head_commit.message }}"
-          git push -u origin ${{matrix.branch}}
-          echo "::debug::syncd from master to ${{matrix.branch}}"
-
+          for f in $FILES; do 
+            git checkout --theirs origin/master -- $f || true
+          done
+          git commit -a -m "[CI] Syncing release automation from master"
+          git push origin
+          echo "::debug::${FILES} syncd for ${{matrix.branch}}"
